### ISSUE TITLE
Class not found when unmarshalling: com.gowtham.library.utils.TrimVideoOptions

### ISSUE THREAD

**Issue by Hassaan-Javed** [a914-gowtham/android-video-trimmer#106]
Complete Logs
```
java.lang.ClassNotFoundException: com.gowtham.library.utils.TrimVideoOptions
                                                                                                    	
at java.lang.Class.classForName(Native Method)
                                                                                                    	
at java.lang.Class.forName(Class.java:454)
                                                                                                    	
at android.os.Parcel.readParcelableCreator(Parcel.java:3351)
                                                                                                    	
at android.os.Parcel.readParcelable(Parcel.java:3285)
                                                                                                    	
at android.os.Parcel.readValue(Parcel.java:3187)
                                                                                                    	
at android.os.Parcel.readArrayMapInternal(Parcel.java:3580)
                                                                                                    	
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
                                                                                                    	
at android.os.BaseBundle.unparcel(BaseBundle.java:236)
                                                                                                    	
at android.os.BaseBundle.getString(BaseBundle.java:1196)
                                                                                                    	
at android.content.Intent.getStringExtra(Intent.java:8889)
                                                                                                    	
at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1131)
                                                                                                    	
at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:897)
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1721)
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1571)
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1523)
                                                                                                    	
at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1671)
                                                                                                    	
at android.os.Binder.execTransactInternal(Binder.java:1190)
                                                                                                    	
at android.os.Binder.execTransact(Binder.java:1159)
                                                                                                    
Caused by: java.lang.ClassNotFoundException: com.gowtham.library.utils.TrimVideoOptions
                                                                                                    	
at java.lang.Class.classForName(Native Method) 
                                                                                                    	
at java.lang.Class.forName(Class.java:454) 
                                                                                                    	
at android.os.Parcel.readParcelableCreator(Parcel.java:3351) 
                                                                                                    	
at android.os.Parcel.readParcelable(Parcel.java:3285) 
                                                                                                    	
at android.os.Parcel.readValue(Parcel.java:3187) 
                                                                                                    	
at android.os.Parcel.readArrayMapInternal(Parcel.java:3580) 
                                                                                                    	
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
                                                                                                    	
at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
                                                                                                    	
at android.os.BaseBundle.getString(BaseBundle.java:1196) 
                                                                                                    	
at android.content.Intent.getStringExtra(Intent.java:8889) 
                                                                                                    	
at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1131) 
                                                                                                    	
at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:897) 
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1721) 
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1571) 
                                                                                                    	
at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1523) 
                                                                                                    	
at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1671) 
                                                                                                    	
at android.os.Binder.execTransactInternal(Binder.java:1190) 
                                                                                                    	
at android.os.Binder.execTransact(Binder.java:1159) 
```

**Comment by Hassaan-Javed** [comment]
@a914-gowtham Would really appreciate if you could check it out. I'm using version: 'com.github.a914-gowtham:Android-video-trimmer:1.6.5'

**Comment by a914-gowtham** [comment]
@Hassaan-Javed could you try using latest version 1.7.19

**Comment by Hassaan-Javed** [comment]
@a914-gowtham I updated to version 1.7.10 as I don't want to update to latest version. I'm now getting this error:

>Execution` failed for task :app:mergeDebugResources.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
> Resource compilation failed. Check logs for details.

The logs are:

`Task :app:mergeDebugResources 
C:\Users\Hassaan\.gradle\caches\transforms-3\3d3ea93359bc8b2de66c2f10b0b579a8\transformed\jetified-android-video-trimmer-1.7.10\res\values\values.xml:172:4: Duplicate value for resource 'attr/position' with config 'DEFAULT' and product ''. Resource was previously defined here: C:\Users\Hassaan\.gradle\caches\transforms-3\3d3ea93359bc8b2de66c2f10b0b579a8\transformed\jetified-android-video-trimmer-1.7.10\res\values\values.xml:32:4: .`

**Comment by Hassaan-Javed** [comment]
Hey I fixed it. The reason for the issue was that I was using library version 2.18.1 of ExoPlayer which wasn't supported with the older versions of AndroidVideoTrimmer as the . I eventually set on using 
android-video-trimmer:1.7.2
