### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libavutil.so" not found

### ISSUE THREAD

**Issue by Kyun-J** [a914-gowtham/Android-video-trimmer#2]
My project is compileSdkVersion 30, minSdkVersion 23.
When I use your library, I get the following error.

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libavutil.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at Jni.FFmpegCmd.<clinit>(FFmpegCmd.java:18)
        at Jni.FFmpegCmd.exec(FFmpegCmd.java:77)
        at com.gowtham.library.ui.ActVideoTrimmer.validateVideo(ActVideoTrimmer.java:449)
        at com.gowtham.library.ui.ActVideoTrimmer.onOptionsItemSelected(ActVideoTrimmer.java:428)
        at android.app.Activity.onMenuItemSelected(Activity.java:4264)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28296)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by a914-gowtham** [comment]
when did you get this error,whether opening the VideoTrim Activity or clicking tick icon to trim the video?

**Comment by a914-gowtham** [comment]
use  implementation 'com.github.a914-gowtham:Android-video-trimmer:1.0.5'
for now and change TrimmerConstants into com.gowtham.library.utils.Constants

**Comment by a914-gowtham** [comment]
issue closed due to non response
