### ISSUE TITLE
java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by thedeveloper19** [a914-gowtham/Android-video-trimmer#45]
In Samsung Galaxy M11 I'm getting this error. But not in all device. Same device working fine. But In one device app is crashing after triming :
here is log:

java.lang.NoClassDefFoundError: 
  at com.gowtham.library.ui.ActVideoTrimmer.lambda$execFFmpegBinary$7$ActVideoTrimmer (ActVideoTrimmer.java:552)
  at com.gowtham.library.ui.-$$Lambda$ActVideoTrimmer$MCPO02d6SpT9CwOEpTbigIE9zLk.run (Unknown Source:6)
  at java.lang.Thread.run (Thread.java:919)

**Comment by a914-gowtham** [comment]
Hi @thedeveloper19  Can you share the full error log?

**Comment by thedeveloper19** [comment]
Sorry but play console provide me only these log.

**Comment by thedeveloper19** [comment]
2021-04-27 07:47:57.750 1431-2151/? E/Parcel: Class not found when unmarshalling: com.gowtham.library.utils.TrimVideoOptions
    java.lang.ClassNotFoundException: com.gowtham.library.utils.TrimVideoOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:765)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:676)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1778)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:607)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1615)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1512)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1466)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1655)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by a914-gowtham** [comment]
Hey, @thedeveloper19  I have made a release with the fix. can you try it and let me know the issue status

**Comment by thedeveloper19** [comment]
Ok, sure. I will try

**Comment by a914-gowtham** [comment]
Closing due to response delay

**Comment by thedeveloper19** [comment]
Still the issue present:
2021-05-03 12:19:00.942 1514-2155/? E/Parcel: Class not found when unmarshalling: com.gowtham.library.utils.TrimVideoOptions
    java.lang.ClassNotFoundException: com.gowtham.library.utils.TrimVideoOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:765)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:676)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1778)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:607)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1615)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1512)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1466)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1655)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
