### ISSUE TITLE
I am suresh, while I taken video from internalstorage video and start to edit but getting crash.please help me

### ISSUE THREAD

**Issue by sureshkumarknila** [a914-gowtham/android-video-trimmer#91]
2022-10-11 11:43:55.651 7483-8246/com.nchant.user E/AndroidRuntime: FATAL EXCEPTION: pool-18-thread-1
    Process: com.nchant.user, PID: 7483
    java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
        at com.gowtham.library.utils.FileUtils.getRealPath(FileUtils.java:26)
        at com.gowtham.library.ui.ActVideoTrimmer.lambda$setDataInView$4$ActVideoTrimmer(ActVideoTrimmer.java:218)
        at com.gowtham.library.ui.-$$Lambda$ActVideoTrimmer$oSNiy720JmS9xLvkSHcIMIc37rE.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by a914-gowtham** [comment]
Could you send the file uri of the video? which you pass here
`TrimVideo.activity(String.valueOf(videoUri))
`

**Comment by a914-gowtham** [comment]
@sureshkumarknila  does it happen only for videos from internal storage?

**Comment by sureshkumarknila** [comment]
> Could you send the file uri of the video? which you pass here `TrimVideo.activity(String.valueOf(videoUri)) `

Uri-file:///storage/emulated/0/WhatsApp/Media/WhatsApp%20Video/VID-20221006-WA0027.mp4

**Comment by sureshkumarknila** [comment]
> Could you send the file uri of the video? which you pass here `TrimVideo.activity(String.valueOf(videoUri)) `
I tried another way below Uri
content://com.nchant.user.provider/images/Video/VID-20221006-WA0027.mp4

**Comment by sureshkumarknila** [comment]
> @sureshkumarknila does it happen only for videos from internal storage?

No both internal and sd card

**Comment by a914-gowtham** [comment]
@sureshkumarknila  thanks. Could you share the device detail as well?

**Comment by sureshkumarknila** [comment]
> @sureshkumarknila thanks. Could you share the device detail as well?
Motrolo one power 
android 10

**Comment by sureshkumarknila** [comment]
@a914-gowtham bro any update?

**Comment by a914-gowtham** [comment]
@sureshkumarknila hey getting file path from uri is not used anymore, so this should be fixed
